project_name: vht

env:
  - GO111MODULE=on

before:
  hooks:
    - go mod tidy
    - go generate ./...
    - go mod download

builds:
  - env:
      - CGO_ENABLED=0
    id: "vht"
    main: ./cmd/vht/main.go
    ldflags:
      - "-extldflags '-static'"
      - "-X 'github.com/ilijamt/vht.BuildVersion={{ .Version }}'"
      - "-X 'github.com/ilijamt/vht.BuildHash={{ .FullCommit }}'"
      - "-X 'github.com/ilijamt/vht.BuildDate={{ .Date }}'"
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goos:
      - linux
      - darwin
      - windows
    flags:
      - -trimpath
    mod_timestamp: '{{ .CommitTimestamp }}'

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - Merge pull request
      - Merge branch

archives:
  - format_overrides:
      - goos: windows
        format: zip

release:
  github:
    owner: ilijamt
    name: vht

brews:
  - repository:
      owner: ilijamt
      name: homebrew-tap
    folder: Formula
    homepage:  https://github.com/ilijamt/vht
    description: A simple vault helper tool that simplifies the usage of Vault
    test: |
      system "#{bin}/vht version"

# chocolateys:
#   - name: vht
#     owners: Ilija Matoski
#     title: Vault Helper Tool
#     authors: Ilija Matoski
#     project_url: https://github.com/ilijamt/vht
#     project_source_url: https://github.com/ilijamt/vht
#     bug_tracker_url: https://github.com/ilijamt/vht/issues
#     docs_url: https://github.com/ilijamt/vht/blob/main/README.md
#     summary: A simple vault helper tool that simplifies the usage of Vault
#     description: |
#       {{ .ProjectName }} installer package
#       A simple vault helper tool that simplifies the usage of Vault.
#       Allows you to search and find data in Vault.
#     api_key: "{{ .Env.CHOCOLATEY_API_KEY }}"
#     source_repo: "https://push.chocolatey.org"