project_name: vht

env:
  - GO111MODULE=on

before:
  hooks:
    - go mod tidy
    - go generate ./...
    - go mod download

builds:
  - env:
      - CGO_ENABLED=0
    id: "vht"
    main: ./cmd/vht/main.go
    ldflags:
      - "-extldflags '-static'"
      - "-X 'github.com/ilijamt/vht.BuildVersion={{ .Version }}'"
      - "-X 'github.com/ilijamt/vht.BuildHash={{ .FullCommit }}'"
      - "-X 'github.com/ilijamt/vht.BuildDate={{ .Date }}'"
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goos:
      - linux
      - darwin
      - windows

checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch

archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip

release:
  github:
    owner: ilijamt
    name: vht

snapcrafts:
  - name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    summary: A simple vault helper tool that simplifies the usage of Vault
    description: |
      Simple tool that allows you to use vault in a way that's not possible from the UI or the command line,
      like recursive searching, tree and recursive delete.
    grade: stable
    confinement: strict
    publish: true
    plugs:
      personal-files:
        read:
          - $HOME/.vault-token

brews:
  - github:
      owner: ilijamt
      name: homebrew-tap
    folder: Formula
    homepage:  https://github.com/ilijamt/vht
    description: A simple vault helper tool that simplifies the usage of Vault
    test: |
      system "#{bin}/vht version"
